---
- name: CREATE Network Security Group for Jumphost access
  delegate_to: localhost
  azure.azcollection.azure_rm_securitygroup:
    resource_group: "rg-{{ extra_platform_name }}"
    name: "nsg-{{ extra_platform_name }}-jumphost"
    location: "{{ extra_location }}"
    tags: "{{ extra_platform_tags }} Name=nsg-{{ extra_platform_name }}-jumphost owner={{ owner }}"
    rules:
      - name: in_allow_mgt_from_vNet
        direction: Inbound
        priority: 100
        source_address_prefix: "{{ extra_jumphost.acl_src_ips }}"
        access: Allow
      - name: in_allow_from_internet
        direction: Inbound
        priority: 101
        protocol: Tcp
        destination_port_range:
          - 22
          - 80
          - 443
          - 5601
        access: Allow
      - name: out_allow_all
        direction: Outbound
        priority: 999
        access: Allow

- name: CREATE Public IP Address for Management NIC
  delegate_to: localhost
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: "rg-{{ extra_platform_name }}"
    allocation_method: Static
    domain_name: "jumphost-{{ extra_jumphost.name }}"
    name: "jumphost-{{ extra_jumphost.name }}"
    location: "{{ extra_location }}"
    sku: 'Standard'
    idle_timeout: 30
    version: 'ipv4'
    tags:
      Name: "management-{{ extra_platform_tags }}-{{ extra_jumphost.name }}"
  register: output_ip_address

- name: CREATE vNIC Management
  delegate_to: localhost
  azure.azcollection.azure_rm_networkinterface:
    resource_group: "rg-{{ extra_platform_name }}"
    name: "nic-{{ extra_platform_name }}-{{ extra_jumphost.name }}-management"
    location: "{{ extra_location }}"
    virtual_network: "vnet-{{ extra_platform_name }}"
    subnet_name: "net-{{ extra_platform_name }}-management"
    create_with_security_group: true
    security_group: "nsg-{{ extra_platform_name }}-jumphost"
    tags: "{{ extra_platform_tags }}
    Name=nic-{{ extra_platform_name }}-{{ extra_jumphost.name }}-management"
    ip_configurations:
      - name: mgt
        private_ip_address: "{{ extra_jumphost.private_ip }}"
        private_ip_allocation_method: 'Static'
        primary: true
        public_ip_address_name: "jumphost-{{ extra_jumphost.name }}"

- name: CREATE VM
  delegate_to: localhost
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: "rg-{{ extra_platform_name }}"
    name: "{{ extra_jumphost.name }}"
    location: "{{ extra_location }}"
    short_hostname: "{{ extra_jumphost.name }}"
    vm_size: "{{ extra_jumphost.vm_size }}"
    os_disk_size_gb: 256
    tags: "{{ extra_platform_tags }}
              Name={{ extra_jumphost.name }}"
    admin_username: "{{ extra_admin_username }}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/{{ extra_admin_username }}/.ssh/authorized_keys"
        key_data: "{{ extra_jumphost.ssh_crt }}"
    image:
      offer: "CentOS"
      publisher: "OpenLogic"
      sku: "7_8-gen2"
      version: "latest"
    managed_disk_type: Premium_LRS
    os_type: Linux
    network_interface_names:
      - "nic-{{ extra_platform_name }}-{{ extra_jumphost.name }}-management"

- name: CMP_OUTPUT
  debug:
    msg: "
    key=dns_mgt;value=jumphost-{{ extra_jumphost.name }}.{{ extra_location }}.cloudapp.azure.com;help=FQDN for management access;
    key=ip_jumphost;value={{ output_ip_address.state.ip_address }};help=Public IP for jumphost access;
    "

- name: Create VM Extension
  delegate_to: localhost
  azure.azcollection.azure_rm_virtualmachineextension:
    name: "extension-{{ extra_jumphost.name }}"
    location: "{{ extra_location }}"
    resource_group: "rg-{{ extra_platform_name }}"
    virtual_machine_name: "{{ extra_jumphost.name }}"
    publisher: 'Microsoft.Azure.Extensions'
    virtual_machine_extension_type: 'CustomScript'
    type_handler_version: 2.0
    protected_settings: '{"commandToExecute": "{{ lookup("template", "jumphost_bootstrapping.jinja2") }}"}'
    settings: '{{ extra_jumphost.extension_file_uri_list }}'
    auto_upgrade_minor_version: true
  when: extra_jumphost.extension_file_uri_list is defined

- name: Create VM Extension - cmd only
  delegate_to: localhost
  azure.azcollection.azure_rm_virtualmachineextension:
    name: "extension-{{ extra_jumphost.name }}"
    location: "{{ extra_location }}"
    resource_group: "rg-{{ extra_platform_name }}"
    virtual_machine_name: "{{ extra_jumphost.name }}"
    publisher: 'Microsoft.Azure.Extensions'
    virtual_machine_extension_type: 'CustomScript'
    type_handler_version: 2.0
    protected_settings: '{"commandToExecute": "{{ lookup("template", "jumphost_bootstrapping.jinja2") }}"}'
    auto_upgrade_minor_version: true
  when: extra_jumphost.extension_file_uri_list is undefined



...